version: '3'

services:
  test:
    build:
      context: .
      dockerfile: docker/Dockerfile-php
    volumes:
      - .:/project
    depends_on:
      - elasticsearch
      - apm
    environment:
      APM_URL: http://apm:8200

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.3
    ports:
      - 9200:9200
    volumes:
      - ./tmp/es-data:/usr/share/elasticsearch/data
    environment:
      JAVA_TOOL_OPTIONS: "-Xms512m -Xmx512m"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9200']
      interval: 5s
      timeout: 100ms
      retries: 10

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.3
    ports:
      - 80:5601
    depends_on:
      - elasticsearch

  apm:
    build:
      context: .
      dockerfile: docker/Dockerfile-apm
    depends_on:
      - elasticsearch
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8200']
      interval: 5s
      timeout: 100ms
      retries: 10
