version: 2

workflows:
  version: 2
  quality-tools:
    jobs:
      - unit-tests:
          context: Generic
      - acceptance-tests:
          context: Generic
      - phpstan:
          context: Generic
      - phpcs:
          context: Generic
      - phpinfection:
          context: Generic

jobs:
  unit-tests:
    docker:
      - image: circleci/php:7.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - project-dependencies-{{ checksum "~/project/composer.lock" }}
            - composer-cache
      - run: make ci-dependencies
      - save_cache:
          key: project-dependencies-{{ checksum "~/project/composer.lock" }}
          paths:
            - ~/project/vendor
      - save_cache:
          key: composer-cache
          paths:
            - ~/.composer/cache
      - run: make test-unit
      - store_test_results:
          path: build/unit
      - store_artifacts:
          path: build/unit

  acceptance-tests:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - project-dependencies-{{ checksum "~/project/composer.lock" }}
            - composer-cache
      - run: docker run --rm --volume $(pwd):/app --entrypoint /bin/bash composer -c "composer config -g github-oauth.github.com $GITHUB_TOKEN && composer install -n -o"
      - save_cache:
          key: project-dependencies-{{ checksum "~/project/composer.lock" }}
          paths:
            - ~/project/vendor
      - save_cache:
          key: composer-cache
          paths:
            - ~/.composer/cache
      - run: make ci-acceptance-environment
      - run: make test-acceptance
      - store_test_results:
          path: build/acceptance
      - store_artifacts:
          path: build/acceptance

  phpinfection:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
          - project-dependencies-{{ checksum "~/project/composer.lock" }}
          - composer-cache
      - run: docker run --rm --volume $(pwd):/app --entrypoint /bin/bash composer -c "composer config -g github-oauth.github.com $GITHUB_TOKEN && composer install -n -o"
      - save_cache:
          key: project-dependencies-{{ checksum "~/project/composer.lock" }}
          paths:
          - ~/project/vendor
      - save_cache:
          key: composer-cache
          paths:
          - ~/.composer/cache
      - run: make test-mutation
      - store_artifacts:
          path: build/phpinfection

  phpstan:
    docker:
      - image: circleci/php:7.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - project-dependencies-{{ checksum "~/project/composer.lock" }}
            - composer-cache
      - run: make ci-dependencies
      - save_cache:
          key: project-dependencies-{{ checksum "~/project/composer.lock" }}
          paths:
            - ~/project/vendor
      - save_cache:
          key: composer-cache
          paths:
            - ~/.composer/cache
      - run: make phpstan

  phpcs:
    docker:
      - image: circleci/php:7.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - project-dependencies-{{ checksum "~/project/composer.lock" }}
            - composer-cache
      - run: make ci-dependencies
      - save_cache:
          key: project-dependencies-{{ checksum "~/project/composer.lock" }}
          paths:
            - ~/project/vendor
      - save_cache:
          key: composer-cache
          paths:
            - ~/.composer/cache
      - run: make phpcs
