version: 2

workflows:
  version: 2
  quality-tools:
    jobs:
      - unit-tests:
          context: Generic
      - acceptance-tests:
          context: Generic
      - phpstan:
          context: Generic
      - phpcs:
          context: Generic

jobs:
  unit-tests:
    docker:
      - image: circleci/php:7.2
    steps:
      - run: sudo composer self-update
      - run: composer config -g github-oauth.github.com $GITHUB_TOKEN
      - checkout

      - restore_cache:
          keys:
            - project-dependencies-{{ checksum "~/project/composer.lock" }}
            - composer-cache

      - run: composer install -n -o
      - save_cache:
          key: project-dependencies-{{ checksum "~/project/composer.lock" }}
          paths:
            - ~/project/vendor
      - save_cache:
          key: composer-cache
          paths:
            - ~/.composer/cache

      - run: mkdir -p ~/phpunit && ./vendor/bin/phpunit --testsuite=unit --log-junit ~/phpunit/unit.xml
      - store_test_results:
          path: ~/phpunit
      - store_artifacts:
          path: ~/phpunit

  acceptance-tests:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - project-dependencies-{{ checksum "~/project/composer.lock" }}
            - composer-cache

      - run: docker run --rm --volume $(pwd):/app --entrypoint /bin/bash composer -c "composer config -g github-oauth.github.com $GITHUB_TOKEN && composer install -a"
      - save_cache:
          key: project-dependencies-{{ checksum "~/project/composer.lock" }}
          paths:
            - ~/project/vendor
      - save_cache:
          key: composer-cache
          paths:
            - ~/.composer/cache

      - run: mkdir -p tmp/test-artifacts
      - run: sudo sysctl -w vm.max_map_count=262144
      - run: docker-compose -f docker-compose-test.yml up -d
      - run: docker-compose -f docker-compose-test.yml run test sh -c "cd /project && vendor/bin/behat -f progress -o std -f junit -o tmp/test-artifacts"
      - store_test_results:
          path: tmp/test-artifacts
      - store_artifacts:
          path: tmp/test-artifacts

  phpstan:
    docker:
      - image: circleci/php:7.2
    steps:
      - run: sudo docker-php-ext-install pcntl
      - run: sudo composer self-update
      - run: composer config -g github-oauth.github.com $GITHUB_TOKEN
      - checkout

      - restore_cache:
          keys:
            - project-dependencies-{{ checksum "~/project/composer.lock" }}
            - composer-cache

      - run: composer install -n -o
      - save_cache:
          key: project-dependencies-{{ checksum "~/project/composer.lock" }}
          paths:
            - ~/project/vendor
      - save_cache:
          key: composer-cache
          paths:
            - ~/.composer/cache
      - run: env $(cat .env.dist | sed -e 's/MODE=dev/MODE=test/' | xargs) ./vendor/bin/phpstan analyse -c phpstan.neon -l max src
      - run: env $(cat .env.dist | sed -e 's/MODE=dev/MODE=test/' | xargs) ./vendor/bin/phpstan analyse -c phpstan.neon -l 4 tests

  phpcs:
    docker:
      - image: circleci/php:7.2
    steps:
      - run: sudo composer self-update
      - run: composer config -g github-oauth.github.com $GITHUB_TOKEN
      - checkout

      - restore_cache:
          keys:
            - project-dependencies-{{ checksum "~/project/composer.lock" }}
            - composer-cache

      - run: composer install -n -o
      - save_cache:
          key: project-dependencies-{{ checksum "~/project/composer.lock" }}
          paths:
            - ~/project/vendor
      - save_cache:
          key: composer-cache
          paths:
            - ~/.composer/cache

      - run: ./vendor/bin/phpcs
